#!/bin/bash

#
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2016 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# Build script for westeros-gl-drm component
# This script builds the project and creates the required .so files
# All build artifacts are stored in the ./build/ directory to keep repo clean
#
# Prerequisites:
#   - Run install-dependencies.sh first to install required packages
#   - Westeros headers should be in build/external/westeros/
#

set -e  # Exit on error

# Color definitions for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored messages
print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to check prerequisites
check_prerequisites() {
    print_info "Checking prerequisites..."
    
    # Check if westeros headers exist (check both locations)
    local WESTEROS_DIR="$BUILD_DIR/external/westeros"
    local REPO_WESTEROS_DIR="$SCRIPT_DIR/external/westeros"
    local REQUIRED_HEADERS=(
        "westeros-compositor.h"
        "westeros-render.h"
    )
    
    # Check in build directory first
    local found_in_build=true
    for header in "${REQUIRED_HEADERS[@]}"; do
        if [ ! -f "$WESTEROS_DIR/$header" ]; then
            found_in_build=false
            break
        fi
    done
    
    # Check in repo directory as fallback
    local found_in_repo=true
    for header in "${REQUIRED_HEADERS[@]}"; do
        if [ ! -f "$REPO_WESTEROS_DIR/$header" ]; then
            found_in_repo=false
            break
        fi
    done
    
    if [ "$found_in_build" = true ]; then
        WESTEROS_INCLUDE_DIR="$WESTEROS_DIR"
        print_info "Using westeros headers from: $WESTEROS_INCLUDE_DIR"
    elif [ "$found_in_repo" = true ]; then
        WESTEROS_INCLUDE_DIR="$REPO_WESTEROS_DIR"
        print_info "Using westeros headers from: $WESTEROS_INCLUDE_DIR"
    else
        print_error "Missing required westeros headers: ${REQUIRED_HEADERS[*]}"
        print_error "Please run install-dependencies.sh first"
        print_info "Headers should be in one of:"
        print_info "  - $WESTEROS_DIR (preferred)"
        print_info "  - $REPO_WESTEROS_DIR (fallback)"
        exit 1
    fi
    
    # Check for required pkg-config packages (matching original build.sh approach)
    local required_pkgs=("glib-2.0" "gthread-2.0" "wayland-client" "wayland-server" "gbm" "libdrm")
    local missing_pkgs=()
    
    for pkg in "${required_pkgs[@]}"; do
        if ! pkg-config --exists "$pkg" 2>/dev/null; then
            missing_pkgs+=("$pkg")
        fi
    done
    
    if [ ${#missing_pkgs[@]} -ne 0 ]; then
        print_error "Missing required packages: ${missing_pkgs[*]}"
        print_error "Please run install-dependencies.sh first"
        exit 1
    fi
    
    print_info "All prerequisites satisfied"
}

# Function to clean previous builds
clean_build() {
    print_info "Cleaning previous build artifacts..."
    
    # Remove build subdirectories but keep external/
    if [ -d "$BUILD_DIR/main" ]; then
        rm -rf "$BUILD_DIR/main"
        print_info "Removed: $BUILD_DIR/main"
    fi
    
    if [ -d "$BUILD_DIR/modules" ]; then
        rm -rf "$BUILD_DIR/modules"
        print_info "Removed: $BUILD_DIR/modules"
    fi
    
    # Clean any autogenerated files in source tree
    cd "$SCRIPT_DIR"
    rm -f configure config.log config.status
    rm -rf autom4te.cache
    rm -f aclocal.m4
    rm -f Makefile.in
    
    # Clean modules subdirectory source files
    if [ -d modules ]; then
        pushd modules &>/dev/null
        rm -f configure config.log config.status config.h.in
        rm -rf autom4te.cache
        rm -f Makefile.in
        
        # Clean resolution module source files
        if [ -d resolution ]; then
            pushd resolution &>/dev/null
            rm -f configure config.log config.status config.h.in
            rm -rf autom4te.cache
            rm -f Makefile.in
            popd &>/dev/null
        fi
        popd &>/dev/null
    fi
    
    print_info "Clean completed"
}

# Function to configure and build modules subdirectory
build_modules() {
    if [ ! -d "$SCRIPT_DIR/modules" ]; then
        print_warn "modules directory not found, skipping"
        return 0
    fi
    
    print_info "Building modules subdirectory..."
    local MODULES_SRC="$SCRIPT_DIR/modules"
    local MODULES_BUILD="$BUILD_DIR/modules"
    
    # Build resolution module first if it exists
    if [ -d "$MODULES_SRC/resolution" ]; then
        print_info "Configuring resolution module..."
        local RESOLUTION_SRC="$MODULES_SRC/resolution"
        local RESOLUTION_BUILD="$BUILD_DIR/modules/resolution"
        
        # Generate configure script in source directory if needed
        pushd "$RESOLUTION_SRC" &>/dev/null
        if [ ! -f configure ]; then
            print_info "Generating resolution module configure script..."
            aclocal
            libtoolize --automake --copy --force
            autoheader
            automake --foreign --add-missing --copy
            autoconf
        fi
        popd &>/dev/null
        
        # Create build directory and configure
        mkdir -p "$RESOLUTION_BUILD"
        pushd "$RESOLUTION_BUILD" &>/dev/null
        
        print_info "Running resolution module configure..."
        "$RESOLUTION_SRC/configure" --prefix=/usr
        
        print_info "Building resolution module..."
        make -j$(nproc)
        
        popd &>/dev/null
        print_info "Resolution module built successfully"
    fi
    
    # Generate configure script for modules in source directory if needed
    pushd "$MODULES_SRC" &>/dev/null
    if [ ! -f configure ]; then
        print_info "Generating modules configure script..."
        aclocal
        libtoolize --automake --copy --force
        autoheader
        automake --foreign --add-missing --copy
        autoconf
    fi
    popd &>/dev/null
    
    # Create build directory and configure
    mkdir -p "$MODULES_BUILD"
    pushd "$MODULES_BUILD" &>/dev/null
    
    print_info "Running modules configure..."
    "$MODULES_SRC/configure" --prefix=/usr
    
    print_info "Building modules..."
    make -j$(nproc)
    
    popd &>/dev/null
    print_info "Modules build completed"
}

# Function to build the main project
build_project() {
    print_info "Building westeros-gl-drm main component..."
    
    # Generate configure script in source directory if needed
    pushd "$SCRIPT_DIR" &>/dev/null
    if [ ! -f configure ]; then
        print_info "Generating configure script..."
        
        # Create m4 directory if it doesn't exist
        mkdir -p m4
        
        print_info "Running aclocal..."
        aclocal -I m4
        
        print_info "Running libtoolize..."
        libtoolize --automake --copy --force
        
        print_info "Running autoheader..."
        autoheader
        
        print_info "Running automake..."
        automake --foreign --add-missing --copy
        
        print_info "Running autoconf..."
        autoconf
    fi
    popd &>/dev/null
    
    # Create main build directory
    mkdir -p "$BUILD_DIR/main"
    pushd "$BUILD_DIR/main" &>/dev/null
    
    # Set include path for westeros headers (using the directory found in check_prerequisites)
    export CFLAGS="${CFLAGS} -I$WESTEROS_INCLUDE_DIR"
    export CPPFLAGS="${CPPFLAGS} -I$WESTEROS_INCLUDE_DIR"
    
    # Configure the project
    print_info "Running configure..."
    print_info "Using westeros headers from: $WESTEROS_INCLUDE_DIR"
    "$SCRIPT_DIR/configure" \
        --prefix=/usr \
        --enable-gbm-modifiers
    
    # Build
    print_info "Building project (using $(nproc) parallel jobs)..."
    make -j$(nproc)
    
    popd &>/dev/null
    print_info "Build completed successfully"
}

# Function to display build information
display_build_info() {
    echo ""
    print_info "======================================"
    print_info "Build Information"
    print_info "======================================"
    
    if [ -d "$BUILD_DIR" ]; then
        echo ""
        print_info "Build directory: $BUILD_DIR"
        echo ""
        print_info "Libraries built:"
        
        if [ -f "$BUILD_DIR/main/.libs/libwesteros_gl.so" ]; then
            echo "  ✓ libwesteros_gl.so (Main GL library)"
        fi
        
        if [ -f "$BUILD_DIR/main/.libs/libwesteros_gl_console_helper.so" ]; then
            echo "  ✓ libwesteros_gl_console_helper.so (Console helper)"
        fi
        
        if [ -f "$BUILD_DIR/modules/resolution/.libs/libresolutionmodule.so" ]; then
            echo "  ✓ libresolutionmodule.so (Resolution module)"
        fi
        
        echo ""
        print_info "Binaries built:"
        
        if [ -f "$BUILD_DIR/main/westeros-gl-console" ] || [ -f "$BUILD_DIR/main/.libs/westeros-gl-console" ]; then
            echo "  ✓ westeros-gl-console"
        fi
        
        echo ""
        print_info "Build artifacts location:"
        echo "  - Main: $BUILD_DIR/main/"
        echo "  - Modules: $BUILD_DIR/modules/"
        if [ -d "$BUILD_DIR/modules/resolution" ]; then
            echo "  - Resolution: $BUILD_DIR/modules/resolution/"
        fi
        echo ""
        print_info "Installation prefix: /usr"
        echo ""
    fi
}

# Function to run tests (if available)
run_tests() {
    print_info "Checking for tests..."
    
    # Check in main build directory
    if [ -d "$BUILD_DIR/main" ]; then
        pushd "$BUILD_DIR/main" &>/dev/null
        if [ -f Makefile ] && grep -q "check:" Makefile; then
            print_info "Running tests..."
            make check
        else
            print_warn "No tests found"
        fi
        popd &>/dev/null
    else
        print_warn "No tests found"
    fi
}

# Function to install the project
install_project() {
    print_info "Installing westeros-gl-drm..."
    
    # Install from build directories
    if [ -d "$BUILD_DIR/main" ]; then
        pushd "$BUILD_DIR/main" &>/dev/null
        print_info "Installing main component..."
        sudo make install
        popd &>/dev/null
    fi
    
    if [ -d "$BUILD_DIR/modules/resolution" ]; then
        pushd "$BUILD_DIR/modules/resolution" &>/dev/null
        print_info "Installing resolution module..."
        sudo make install
        popd &>/dev/null
    fi
    
    if [ -d "$BUILD_DIR/modules" ]; then
        pushd "$BUILD_DIR/modules" &>/dev/null
        if [ -f Makefile ]; then
            print_info "Installing modules..."
            sudo make install
        fi
        popd &>/dev/null
    fi
    
    # Update library cache
    print_info "Updating library cache..."
    sudo ldconfig
    
    print_info "Installation completed"
}

# Main execution
main() {
    echo ""
    print_info "======================================"
    print_info "Westeros GL DRM - Build Script"
    print_info "======================================"
    echo ""
    
    # Get script directory
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    cd "$SCRIPT_DIR"
    
    # Set build directory (all builds happen here)
    BUILD_DIR="$SCRIPT_DIR/build"
    
    # Create build directory if it doesn't exist
    mkdir -p "$BUILD_DIR"
    
    # Parse command line arguments
    CLEAN_ONLY=false
    SKIP_INSTALL=false
    RUN_TESTS=false
    SKIP_CLEAN=false
    
    while [[ $# -gt 0 ]]; do
        case $1 in
            --clean)
                CLEAN_ONLY=true
                shift
                ;;
            --skip-clean)
                SKIP_CLEAN=true
                shift
                ;;
            --skip-install)
                SKIP_INSTALL=true
                shift
                ;;
            --test)
                RUN_TESTS=true
                shift
                ;;
            --help)
                echo "Usage: $0 [OPTIONS]"
                echo ""
                echo "Options:"
                echo "  --clean          Clean build artifacts and exit"
                echo "  --skip-clean     Skip cleaning before build"
                echo "  --skip-install   Build but don't install"
                echo "  --test           Run tests after build"
                echo "  --help           Show this help message"
                echo ""
                echo "Prerequisites:"
                echo "  Run install-dependencies.sh first to install required packages"
                echo ""
                echo "Build artifacts are stored in: ./build/"
                echo "  - ./build/main/              Main component build"
                echo "  - ./build/modules/           Modules build"
                echo "  - ./build/modules/resolution/  Resolution module build"
                echo "  - ./build/external/westeros/   Westeros headers (from install-dependencies.sh)"
                echo ""
                exit 0
                ;;
            *)
                print_error "Unknown option: $1"
                echo "Use --help for usage information"
                exit 1
                ;;
        esac
    done
    
    # Clean if requested
    if [ "$CLEAN_ONLY" = true ]; then
        clean_build
        print_info "Clean completed. Exiting."
        exit 0
    fi
    
    # Check prerequisites
    check_prerequisites
    
    # Clean previous build unless skipped
    if [ "$SKIP_CLEAN" = false ]; then
        clean_build
    else
        print_warn "Skipping clean (--skip-clean flag set)"
    fi
    
    # Build modules
    build_modules
    
    # Build main project
    build_project
    
    # Run tests if requested
    if [ "$RUN_TESTS" = true ]; then
        run_tests
    fi
    
    # Display build information
    display_build_info
    
    # Install if not skipped
    if [ "$SKIP_INSTALL" = false ]; then
        install_project
        
        echo ""
        print_info "======================================"
        print_info "Build & Install Completed Successfully!"
        print_info "======================================"
        echo ""
        
        print_info "Usage examples:"
        echo "  1. Run with LD_PRELOAD:"
        echo "     LD_PRELOAD=libwesteros_gl.so westeros --renderer libwesteros_render_gl.so"
        echo ""
        echo "  2. Run console application:"
        echo "     westeros-gl-console"
        echo ""
    else
        print_warn "Skipping installation (--skip-install flag set)"
        
        echo ""
        print_info "======================================"
        print_info "Build Completed Successfully!"
        print_info "======================================"
        echo ""
        
        print_info "To install manually:"
        echo "  cd $BUILD_DIR/main && sudo make install"
        if [ -d "$BUILD_DIR/modules/resolution" ]; then
            echo "  cd $BUILD_DIR/modules/resolution && sudo make install"
        fi
        if [ -d "$BUILD_DIR/modules" ]; then
            echo "  cd $BUILD_DIR/modules && sudo make install"
        fi
        echo "  sudo ldconfig"
        echo ""
    fi
    
    print_info "Build artifacts are located in: $BUILD_DIR"
    echo ""
}

# Run main function
main "$@"
